networks:
  n8n:

services:
   # ✅ Kokoro GPU FastAPI
  kokoro-fastapi-gpu:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    container_name: kokoro-fastapi-gpu
    restart: unless-stopped
    networks:
      - n8n
    ports:
      - "8880:8880"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # ✅ KokoroTTS Web Interface
  tts-web:
    build: ./app
    container_name: tts-web
    restart: unless-stopped
    networks:
      - n8n
    ports:
      - "3000:3000"
    environment:
      - KOKORO_API_URL=http://kokoro-fastapi-gpu:8880
    depends_on:
      - kokoro-fastapi-gpu
volumes:

