networks:
  n8n:

services:
   # ✅ Kokoro CPU FastAPI
  kokoro-fastapi-cpu:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: kokoro-fastapi-cpu
    restart: unless-stopped
    networks:
      - n8n
    ports:
      - "8880:8880"

  # ✅ KokoroTTS Web Interface
  tts-web:
    build: ./app
    container_name: tts-web
    restart: unless-stopped
    networks:
      - n8n
    ports:
      - "3000:3000"
    environment:
      - KOKORO_API_URL=http://kokoro-fastapi-cpu:8880
    depends_on:
      - kokoro-fastapi-cpu
volumes:

